masters = gentoo haskell
repo-name = cstew-overlay
cache-formats = md5-dict
manifest-hashes = SHA512 BLAKE2B
manifest-required-hashes = BLAKE2B
thin-manifests = true
update-changelog = true
use-manifests = strict
eapis-banned = 0 1 2 3 4 5 6 7