# Copyright 1999-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.0.0

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="An implementation of the Futhark data format"
HOMEPAGE="https://hackage.haskell.org/package/futhark-data"

LICENSE="ISC"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/bytestring-to-vector-0.3.0.1:=[profile?]
	>=dev-haskell/half-0.3:=[profile?]
	>=dev-haskell/megaparsec-9.0.0:=[profile?]
	>=dev-haskell/scientific-0.3.6:=[profile?]
	>=dev-haskell/text-1.2.2.2:=[profile?]
	>=dev-haskell/vector-0.12:=[profile?]
	>=dev-haskell/vector-binary-instances-0.2.2.0:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/quickcheck-2.8
		dev-haskell/tasty
		dev-haskell/tasty-hunit
		dev-haskell/tasty-quickcheck )
"
